# Generated by Django 5.0 on 2023-12-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='track',
        ),
        migrations.AddField(
            model_name='album',
            name='track',
            field=models.ManyToManyField(related_name='album_track', to='catalog.track'),
        ),
    ]
