# Generated by Django 5.0 on 2023-12-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_album_track_album_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='num_of_tracks',
            field=models.IntegerField(verbose_name='Number of tracks'),
        ),
    ]
